-- CreateTable
CREATE TABLE "KernelProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "w1" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "w2" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
    "w3" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "w4" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
    "w5" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
    "w6" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "KernelProfile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "KernelProfile_userId_key" ON "KernelProfile"("userId");

-- AddForeignKey
ALTER TABLE "KernelProfile" ADD CONSTRAINT "KernelProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
